version: 40
jobs:
- name: Publish Site
  steps:
  - !CheckoutStep
    name: Get Code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !PublishSiteStep
    name: Publish Site
    artifacts: '*'
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: Push to Github
  steps:
  - !CheckoutStep
    name: Get Code
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: SUCCESSFUL
    optional: false
  - !PushRepository
    name: Push to Github
    remoteUrl: https://github.com/Limo123123/whatslim
    userName: Limo123123
    passwordSecret: gh
    force: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - !BranchUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
